name: CI
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

env:
  CI: true
  PNPM_CACHE_FOLDER: .pnpm-store

permissions: {}
jobs:
  build:
    permissions:
      contents: write # to create release (changesets/action)
      pull-requests: write # to create pull request (changesets/action)
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: checkout code repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v4.0.0
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: pnpm

      - name: git config
        run: git config --global url."https://github.com/".insteadOf 'git@github.com:'

      - name: install dependencies
        run: pnpm install --frozen-lockfile

      - name: build style
        run: make build
